### ISSUE TITLE
First Time Quick Setup not working

### ISSUE THREAD

**Issue by rstol** [Battery-Intelligence-Lab/galv#115]
**Describe the bug**
I followed the steps of the first time quick setup until the point of running the Galv server with `docker compose up`. In the postgres container I get the error:
`password authentication failed for user "postgres"` `User "postgres" has no password assigned.`. 

**To Reproduce**
Running Docker desktop version: 20.10.16.
1. Clone the git repo `git clone git@github.com:Battery-Intelligence-Lab/galv.git`
2. Set up `.env.secret` file with variables
3. Run `docker compose build`
4. Run `docker compose up`

**Expected behavior**
The server should be running without fatal error and `http://localhost` in the browser should be rendering the front-end.  

**Additional context**
I started the postgres container shell to verify that the `POSTGRES_PASSWORD`is set in the container environment (running `env` command).  

My `docker compose config` looks like:
``` 
name: galv
services:
  app:
    build:
      context: /Users/romeostoll/Documents/Work/Eightinks/galv/backend
      dockerfile: Dockerfile
    command:
    - ./server.sh
    depends_on:
      postgres:
        condition: service_started
    environment:
      DJANGO_SECRET_KEY: super_secret_password
      DJANGO_SUPERUSER_PASSWORD: secret_password
      DJANGO_SUPERUSER_USERNAME: admin
      FRONTEND_VIRTUAL_HOST: http://localhost,https://localhost
      GALV_DATA_PATH: ./.run/data/galv
      GALV_HARVESTER_TEST_PATH: ./.run/test_datafiles
      LETSENCRYPT_EMAIL: oxfordrse@gmail.com
      LETSENCRYPT_HOST: api.localhost
      LETSENCRYPT_TEST: "true"
      NODE_OPTIONS: --openssl-legacy-provider
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      VIRTUAL_HOST: api.localhost
      VIRTUAL_HOST_ROOT: localhost
    image: app
    networks:
      default: null
    restart: unless-stopped
    volumes:
    - type: bind
      source: /Users/romeostoll/Documents/Work/Eightinks/galv/.static_files
      target: /static
      bind:
        create_host_path: true
    working_dir: /usr/app
  frontend:
    build:
      context: /Users/romeostoll/Documents/Work/Eightinks/galv/frontend
      dockerfile: Dockerfile
      args:
        VIRTUAL_HOST_ROOT: localhost
    depends_on:
      app:
        condition: service_started
    environment:
      GALV_DATA_PATH: ./.run/data/galv
      GALV_HARVESTER_TEST_PATH: ./.run/test_datafiles
      LETSENCRYPT_EMAIL: oxfordrse@gmail.com
      LETSENCRYPT_HOST: localhost
      LETSENCRYPT_TEST: "true"
      NODE_OPTIONS: --openssl-legacy-provider
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      VIRTUAL_HOST: localhost
      VIRTUAL_HOST_ROOT: localhost
    image: frontend
    networks:
      default: null
    restart: unless-stopped
  nginx-proxy:
    build:
      context: /Users/romeostoll/Documents/Work/Eightinks/galv/nginx-proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    depends_on:
      app:
        condition: service_started
      frontend:
        condition: service_started
    environment:
      DEFAULT_HOST: localhost
      TRUST_DOWNSTREAM_PROXY: "true"
    networks:
      default: null
    ports:
    - mode: ingress
      target: 443
      published: "443"
      protocol: tcp
    - mode: ingress
      target: 80
      published: "80"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /Users/romeostoll/Documents/Work/Eightinks/galv/.static_files
      target: /app/static
      bind:
        create_host_path: true
    - type: bind
      source: /Users/romeostoll/Documents/Work/Eightinks/galv/.certs
      target: /etc/nginx/certs
      bind:
        create_host_path: true
    - type: bind
      source: /Users/romeostoll/Documents/Work/Eightinks/galv/.html
      target: /usr/share/nginx/html
      bind:
        create_host_path: true
    - type: volume
      source: vhost
      target: /etc/nginx/vhost.d
      volume: {}
    - type: bind
      source: /var/run/docker.sock
      target: /tmp/docker.sock
      read_only: true
      bind:
        create_host_path: true
  nginx-proxy-acme-companion:
    depends_on:
      nginx-proxy:
        condition: service_started
    environment:
      GALV_DATA_PATH: ./.run/data/galv
      GALV_HARVESTER_TEST_PATH: ./.run/test_datafiles
      LETSENCRYPT_EMAIL: oxfordrse@gmail.com
      LETSENCRYPT_TEST: "true"
      NGINX_PROXY_CONTAINER: nginx-proxy
      NODE_OPTIONS: --openssl-legacy-provider
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      VIRTUAL_HOST_ROOT: localhost
    image: nginxproxy/acme-companion
    networks:
      default: null
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /Users/romeostoll/Documents/Work/Eightinks/galv/.certs
      target: /etc/nginx/certs
      bind:
        create_host_path: true
    - type: bind
      source: /Users/romeostoll/Documents/Work/Eightinks/galv/.html
      target: /usr/share/nginx/html
      bind:
        create_host_path: true
    - type: volume
      source: vhost
      target: /etc/nginx/vhost.d
      volume: {}
    - type: volume
      source: acme
      target: /etc/acme.sh
      volume: {}
  postgres:
    environment:
      DJANGO_SECRET_KEY: super_secret_password
      DJANGO_SUPERUSER_PASSWORD: secret_password
      DJANGO_SUPERUSER_USERNAME: admin
      GALV_DATA_PATH: ./.run/data/galv
      GALV_HARVESTER_TEST_PATH: ./.run/test_datafiles
      LETSENCRYPT_EMAIL: oxfordrse@gmail.com
      LETSENCRYPT_TEST: "true"
      NODE_OPTIONS: --openssl-legacy-provider
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      VIRTUAL_HOST_ROOT: localhost
    image: postgres:14
    networks:
      default: null
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
    - type: bind
      source: /Users/romeostoll/Documents/Work/Eightinks/galv/.run/data/galv
      target: /var/lib/postgresql/data
      bind:
        create_host_path: true
networks:
  default:
    name: galv_default
volumes:
  acme:
    name: galv_acme
  vhost:
    name: galv_vhost
```
